


NAME        = easyfind
CXX         = c++
CXXFLAGS    = -Wall -Wextra -Werror -std=c++98

SRCS        = main.cpp easyfind.cpp
OBJS        = $(SRCS:.cpp=.o)



all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS)  $(OBJS) -o $(NAME) 

%.o:%.cpp easyfind.h
	$(CXX) $(CXXFLAGS) -c $< -o $@


clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

